- name: Install docker on app
  hosts: app
  become: true
  roles:
    - geerlingguy.docker


- name: Install PostgreSQL
  hosts: database
  become: true
  vars:
    postgresql_version: "{{ hostvars[inventory_hostname].version }}"
    postgresql_data_dir: "{{ hostvars[inventory_hostname].data }}{{ postgresql_version }}/main"
  roles:
    - geerlingguy.postgresql
